sudo: false
dist: trusty

language: python

python:
  - "3.6"

before_install:
  - export
  - ls /opt/python/
  - /opt/python/3.6/bin/python --version

install:
  - /opt/python/3.6/bin/python -m venv ./venv
  - source ./venv/bin/activate
  - which python
  - pip install --upgrade pip
  - pip install wheel
  - pip install --no-cache -e .
  - pip install -r requirements_dev.txt

script:
  - which python
  - pytest -s tests
    #  - tests/install_test.sh
